### ISSUE TITLE
Player turns off when battery is full.

### ISSUE THREAD

**Issue by brud** [Lurker00/DX90-firmware#2]
I change two batteries, and give the same result.

**Comment by brud** [comment]
Sorry, it's rockbox issue.

**Comment by napych** [comment]
Actually it's not. Remove configuration file in rockbox folder or check your settings.

**Comment by brud** [comment]
@napych thx for response, i remobe the cfg file, this issue has gone, but issue with pause stil there... Maybe its because buffer size too small? I have a 64 Gb card in player.

**Comment by napych** [comment]
@brud Try latest rockbox build from http://napych.com/other/rockbox-for-ibasso-dx90/official-rockbox-binary-builds/

**Comment by brud** [comment]
@napych I already use it :)
I install rockbox from your site two weeks ago.

**Comment by napych** [comment]
@brud Try to re-format your SD card with exFAT. Does problem persist?

**Comment by brud** [comment]
@napych it's already in exFAT
