### ISSUE TITLE
2.5.1 USB DAC in Linux issues

### ISSUE THREAD

**Issue by Dachtire** [Lurker00/DX90-firmware#4]
1. With DAC in Linux, there is a popping sound frequently and sound delay with video in 2.5.1. According to the [link](https://www.head-fi.org/threads/the-dx90-by-ibasso-sound-impressions-new-firmware-2-5-1.714421/page-201), I test 2.3.0 and it works fine in Linux without the problems.
2. I first guess the problems are cause by the default setting of 32bit 48000Hz, because Windows default setting is the same with problems, when I change the setting to 16bit 44100Hz it works fine.
3. I run the command in Linux both 2.5.1 and 2.3.0 come out the same result.
`$ pactl list short sinks `
`alsa_output.usb-rockchip_DX90_0123456789ABCDEF-00.analog-stereo	module-alsa-card.c	s32le 2ch 48000Hz`
Then I guess the problem is cause by firmware.
4. I find both 2.5.1 and 2.3.0 in the /proc/asound/DX90/stream0 is the same "Format: S32_LE", 
and it show that DX90 only support 32bit 48000Hz,so i can't change it in /etc/pulse/daemon.conf,  but that's not true because DX90 can work 16-32bit 44100-192000Hz in Windows. 
5. I unzip the update.img and tried to moditified the firmware to fix the problems but i don't know which part is different between 2.3.0 and 2.5.1. And I also want to moditified the config of bit rate and sample rate of DX90 in Linux to let it support like Windows.
6. I'm new to the firmware and I want to learn about it, can u tell me how to do or moditified a new one to show me how to do.

**Comment by Lurker00** [comment]
I should have disabled issue reporting here, because it is vaste of your time: I can't change the basic functionality, as it is said in the disclaimer. Nor I provide any support for iBasso DAPs.
